import { createFileRoute, Link } from "@tanstack/react-router";
import { CalendarCheck, CreditCard, IndianRupee, Video } from "lucide-react";
import { AdminShell } from "@/components/admin-shell";
import { AuthGuard } from "@/components/auth-guard";
import { StatusBadge } from "@/components/status-badge";
import { AdminLoading } from "@/components/admin-loading";
import { useClinicData } from "@/hooks/use-clinic-data";
import { Button } from "@/components/ui/button";
import { Table,TableBody,TableCell,TableHead,TableHeader,TableRow } from "@/components/ui/table";

type Appointment={id:string;patient_name:string;service:string;appointment_date:string;appointment_time:string;status:string};
export const Route=createFileRoute("/admin")({head:()=>({meta:[{title:"Doctor Dashboard | BrightSmile"},{name:"description",content:"Clinic operations dashboard."}]}),component:Dashboard});
function Dashboard(){const {data,loading}=useClinicData<Appointment>("appointments");const paid=data.filter(a=>a.status==="PAID").length;const completed=data.filter(a=>a.status==="COMPLETED").length;const upcoming=data.filter(a=>a.status!=="CANCELLED"&&a.status!=="COMPLETED").slice(0,6);return <AuthGuard><AdminShell title="Dashboard" subtitle="A live view of your virtual clinic"><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[[CalendarCheck,"Total bookings",data.length],[IndianRupee,"Paid consults",paid],[Video,"Upcoming",upcoming.length],[CreditCard,"Completed",completed]].map(([Icon,label,value])=>{const I=Icon as typeof CalendarCheck;return <div key={label as string} className="metric-card"><span className="metric-icon"><I/></span><p>{label as string}</p><strong>{value as number}</strong></div>})}</div><section className="mt-7 overflow-hidden rounded-2xl border border-border bg-background"><div className="flex items-center justify-between border-b border-border p-5"><div><h2 className="font-display text-xl font-bold">Upcoming consultations</h2><p className="mt-1 text-sm text-muted-foreground">Automatically refreshes when bookings change</p></div><Button variant="outline" asChild><Link to="/admin/appointments">View all</Link></Button></div>{loading?<AdminLoading/>:<Table><TableHeader><TableRow><TableHead>Patient</TableHead><TableHead>Service</TableHead><TableHead>Date & time</TableHead><TableHead>Status</TableHead></TableRow></TableHeader><TableBody>{upcoming.map(a=><TableRow key={a.id}><TableCell className="font-semibold">{a.patient_name}</TableCell><TableCell>{a.service}</TableCell><TableCell>{a.appointment_date} · {a.appointment_time}</TableCell><TableCell><StatusBadge status={a.status}/></TableCell></TableRow>)}{!upcoming.length&&<TableRow><TableCell colSpan={4} className="h-28 text-center text-muted-foreground">No upcoming consultations yet.</TableCell></TableRow>}</TableBody></Table>}</section></AdminShell></AuthGuard>}