import { createFileRoute, useNavigate } from "@tanstack/react-router";
import { useState } from "react";
import { Chrome, LockKeyhole, Stethoscope } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { supabase } from "@/integrations/supabase/client";
import { lovable } from "@/integrations/lovable";

export const Route = createFileRoute("/auth")({ head: () => ({ meta: [{ title: "Sign in | BrightSmile" }, { name: "description", content: "Sign in or create your BrightSmile patient account." }] }), component: AuthPage });

function AuthPage() { const navigate=useNavigate(); const [mode,setMode]=useState<"login"|"signup">("login"); const [name,setName]=useState(""); const [email,setEmail]=useState(""); const [password,setPassword]=useState(""); const [error,setError]=useState(""); const [loading,setLoading]=useState(false);
  const submit=async(e:React.FormEvent)=>{e.preventDefault();setError("");setLoading(true); const result=mode==="signup"?await supabase.auth.signUp({email,password,options:{data:{name},emailRedirectTo:window.location.origin}}):await supabase.auth.signInWithPassword({email,password}); setLoading(false); if(result.error){setError(result.error.message);return;} if(mode==="signup"&&!result.data.session){setError("Check your email to confirm your account.");return;} navigate({to:"/book"});};
  const google=async()=>{const result=await lovable.auth.signInWithOAuth("google",{redirect_uri:`${window.location.origin}/book`});if(result.error)setError(result.error.message);};
  return <main className="auth-wash grid min-h-screen place-items-center px-5 py-12"><div className="w-full max-w-md"><a href="/" className="mb-8 flex items-center justify-center gap-3 font-display text-xl font-bold"><span className="grid size-11 place-items-center rounded-xl bg-primary text-primary-foreground"><Stethoscope /></span>BrightSmile Virtual</a><div className="rounded-3xl border border-border bg-background/90 p-7 shadow-2xl shadow-primary/10 backdrop-blur md:p-9"><span className="mx-auto grid size-12 place-items-center rounded-2xl bg-primary/10 text-primary"><LockKeyhole /></span><h1 className="mt-5 text-center font-display text-3xl font-bold">{mode==="login"?"Welcome back":"Create patient account"}</h1><p className="mt-2 text-center text-sm text-muted-foreground">{mode==="login"?"Sign in to manage your care":"A secure account is required to book"}</p><Button className="mt-7 w-full" variant="outline" size="lg" onClick={google}><Chrome /> Continue with Google</Button><div className="my-6 flex items-center gap-3 text-xs text-muted-foreground"><span className="h-px flex-1 bg-border"/>OR<span className="h-px flex-1 bg-border"/></div><form className="space-y-4" onSubmit={submit}>{mode==="signup"&&<div><Label htmlFor="name">Full name</Label><Input id="name" className="mt-2 h-11" value={name} onChange={e=>setName(e.target.value)} required minLength={2} maxLength={100}/></div>}<div><Label htmlFor="email">Email</Label><Input id="email" type="email" className="mt-2 h-11" value={email} onChange={e=>setEmail(e.target.value)} required maxLength={255}/></div><div><Label htmlFor="password">Password</Label><Input id="password" type="password" className="mt-2 h-11" value={password} onChange={e=>setPassword(e.target.value)} required minLength={8} maxLength={72}/></div>{error&&<p className="rounded-lg bg-destructive/10 p-3 text-sm text-destructive">{error}</p>}<Button className="w-full" size="lg" disabled={loading}>{loading?"Please wait…":mode==="login"?"Sign in":"Create account"}</Button></form><button className="mt-6 w-full text-sm font-medium text-primary" onClick={()=>{setMode(mode==="login"?"signup":"login");setError("");}}>{mode==="login"?"New patient? Create an account":"Already registered? Sign in"}</button></div></div></main>;
}